---
# tasks file for 2PRecuperatorio

- name: "Rol: 2PRecuperatorio"
  debug:
    msg: "Inicio de tareas dentro del Rol: 2PRecuperatorio"

- name: "Crear directorios en /tmp/alumno/"
  file:
    path: "/tmp/alumno/"
    state: directory
    mode: '0775'
    recurse: yes

- name: "Agrego archivo desde template"
  template:
    src: datos.j2
    dest: /tmp/alumno/datos.txt

